name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install platform
      run:
        pio platform install atmelsam
    - name: Install lib lcd
      run: pio lib -g install seeed-studio/Seeed_Arduino_LCD@1.6.0
    - name: Install lib neo_pixel
      run: pio lib -g install https://github.com/adafruit/Adafruit_NeoPixel/archive/refs/tags/1.8.7.zip
    - name: Run PlatformIO
      run: pio ci -e seeed_wio_terminal
